# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Story
name: tfmustang
email: limuijin@gmail.com
description: TF-mustang's site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tfmustang.github.io" # the base hostname & protocol for your site
twitter_username: tfmustang1
github_username:  tfmustang

# Build settings
kramdown:
 input: GFM
#gems: ["emoji_for_jekyll"]

# serve
host: 192.168.0.12

theme: jekyll-theme-modernist
